version: "3.8"

services:
  mariadb:
    build: code/database/mariaDB/.
    image: mariadb:push-pull
    environment:
      MYSQL_ROOT_PASSWORD: cc-pushpull
    ports:
      - "3306"
  
  database:
    build: code/database/.
    image: logicadb:1.0.0
    environment:
      DB_PASSWORD: 'cc-pushpull'
      DB_HOST: mariadb
    depends_on:
      - mariadb
    ports:
      - "3001"
  
  natssrv:
    build: code/cola/.
    ports:
      - "4222"
    command: -js
  
  worker:
    build: code/worker/.
    environment:
        NATS_ENDPOINT: natssrv:4222
        DB_ENDPOINT: tcp://database:3001
    depends_on:
      - natssrv
      - database
  
  frontend:
    build: code/frontend/.
    environment:
        WORKER_ENDPOINT: natssrv:4222
        DB_ENDPOINT: tcp://database:3001
        HTTP_REST_API_PORT: 3000
    depends_on:
      - natssrv
      - worker
      - database
    ports:
      - "3000:3000"

    
