version: "3.8"

services:
  mariadb:
    build: code/database/mariaDB/.
    image: mariadb:push-pull
    environment:
      MYSQL_ROOT_PASSWORD: cc-pushpull
    ports:
      - "3306:3306"
  
  database:
    build: code/database/.
    image: logicadb:1.0.0
    environment:
      DB_PASSWORD: 'cc-pushpull'
      DB_HOST: mariadb
    depends_on:
      - mariadb
    ports:
      - "3001:3001"

  frontend:
    build: code/frontend/.
    image: frontend:1.0.0
    environment:
      HTTP_REST_API_PORT: 3000
      WORKER_ENDPOINT: "172.17.0.1:4222"
      DB_ENDPOINT: "tcp://172.17.0.1:3001"
    ports:
      - "3000:3000"
    depends_on:
      - database
      - cola

  worker:
    build: code/worker/.
    image: worker:1.0.0
    environment:
      NATS_ENDPOINT: "172.17.0.1:4222"
      DB_ENDPOINT: "tcp://172.17.0.1:3001"
    depends_on:
      - database
      - cola

  cola:
    build: code/cola/.
    ports:
      - "4222:4222"



    
