CREATE DATABASE pushpull;
USE pushpull;
CREATE TABLE JSON_OBJECT(
	Id MEDIUMINT NOT NULL AUTO_INCREMENT,
      Propietario VARCHAR(15) NOT NULL,
      MyData JSON NOT NULL,
      CHECK (JSON_VALID(MyData)),
      PRIMARY KEY (Id)
);

INSERT INTO JSON_OBJECT
VALUES(NULL, 'SANTIAGO', '{"name": "Santi", "fecha": "12/01/2022", "isAdmin": true}');